package vista;


import dao.RegistroPerDao;
import dto.RegistroPer;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Notebook-
 */
public class RegistroForm extends javax.swing.JInternalFrame {
    private RegistroPerDao RuDAO = new RegistroPerDao();
    private RegistroPer dto; 
    /**
     * Creates new form Registro
     */
    public RegistroForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtclave = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        txtcelular = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtcargo = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtconclave = new javax.swing.JPasswordField();
        conclave = new javax.swing.JLabel();

        setClosable(true);

        jPanel2.setLayout(null);
        jPanel2.add(txtclave);
        txtclave.setBounds(50, 310, 200, 30);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 0, 80, 30);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("Apellido");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(270, 0, 80, 30);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("Edad");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 90, 60, 20);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setText("Celular");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(270, 90, 70, 20);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setText("Correo");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 170, 70, 20);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("Cargo");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(280, 170, 80, 30);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setText("Clave");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 280, 60, 20);
        jPanel2.add(txtnombre);
        txtnombre.setBounds(30, 30, 190, 30);
        jPanel2.add(txtapellido);
        txtapellido.setBounds(310, 30, 180, 30);
        jPanel2.add(txtedad);
        txtedad.setBounds(70, 120, 70, 30);
        jPanel2.add(txtcelular);
        txtcelular.setBounds(310, 120, 190, 30);
        jPanel2.add(txtcorreo);
        txtcorreo.setBounds(40, 200, 220, 30);
        jPanel2.add(txtcargo);
        txtcargo.setBounds(330, 200, 180, 30);

        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnagregar);
        btnagregar.setBounds(620, 60, 90, 50);

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnlimpiar);
        btnlimpiar.setBounds(620, 150, 90, 50);

        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnnuevo);
        btnnuevo.setBounds(620, 260, 90, 60);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("Confirmar Clave");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(290, 260, 150, 40);
        jPanel2.add(txtconclave);
        txtconclave.setBounds(330, 310, 190, 30);

        conclave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1-37syk5TT1FBYcgxRPRe4NQ.jpeg"))); // NOI18N
        conclave.setText("jLabel3");
        jPanel2.add(conclave);
        conclave.setBounds(0, 0, 790, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        String nom, apell,correo,carg,clav;
        
        
        int numcel = Integer.parseInt(txtcelular.getText());
        int edad = Integer.parseInt(txtedad.getText());
        nom = txtnombre.getText();
        apell = txtapellido.getText();
        correo = txtcorreo.getText();
        carg = txtcargo.getText();
        clav = txtclave.getText();
        
        dto = new RegistroPer(nom, apell, edad, numcel, correo, carg, clav);
        if(RuDAO.create(dto)>0){
            JOptionPane.showMessageDialog(null, "Registro guardado");
            btnlimpiar.setEnabled(true);
            btnnuevo.setEnabled(true);
        
        }else{
            JOptionPane.showMessageDialog(null, "Error al registro");
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        
        txtapellido.setText(null);
        txtcargo.setText(null);
        txtcelular.setText(null);
        txtclave.setText(null);
        txtcorreo.setText(null);
        txtedad.setText(null);
        txtnombre.setText(null);
        txtconclave.setText(null);
        
        txtnombre.requestFocus();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        txtapellido.setEditable(true);
        txtcargo.setEditable(true);
        txtcelular.setEditable(true);
        txtclave.setEditable(true);
        txtcorreo.setEditable(true);
        txtedad.setEditable(true);
        txtnombre.setEditable(true);
        txtconclave.setEditable(true);
        
        btnagregar.setEnabled(true);
        btnlimpiar.setEnabled(true);
        
        btnnuevo.setEnabled(false);
        txtnombre.requestFocus();
        
    }//GEN-LAST:event_btnnuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel conclave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JPasswordField txtconclave;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
